spring:
  application:
    name: gateway
    clould:
      gateway:
        routes:
          - id: agenda
            uri: lb://agenda
            predicates:
              - path=/agenda/**

          - id: funcionario
            uri: lb://funcionario
            predicates:
              - path=/funcionario/**

          - id: sala
            uri: lb://sala
            predicates:
              - path=/sala/**

server:
  port: ${PORTA:8080}
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
