server:
  port: 8092
  error:
    include-message: always

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# datasource
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./ms-sala/data/bd-sala
    username: sa
    password:
  # jpa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  # h2
  h2:
    console:
      enabled: true
      path: /h2-console

  #proj-config
  proj-config:
    console: true
    path: /proj-config

management:
    endpoints:
        enabled-by-default: false
        web:
            base-path: /actuator
            exposure:
                include: "health,prometheus"
    endpoint:
        health:
            enabled: true
            show-details: always
        prometheus:
enabled: true