server:
    port: 9090

spring:
    profiles:
        active: native
clould:
    config:
        server:
            native:
                search-locations: C:/Users/Cristian/Desktop/proj-agenda-micro-services-master/proj-config
